### PR TITLE
Smooth out the setup experience

### PR DESCRIPTION
**Pull request by mgovea**
I think the template makes startup very easy and solves some issues I had when I was starting with my plugin. I ported Ride Price Manager to use your template because I want to be a good example to new modders: when they look at my plugin, they'll be directed to use your stuff.

During that process, I found some points of confusion or complication that I thought it'd be straightforward to fix:

- Some things in README weren't obvious to me, so I added some more examples (especially the file path stuff).
- `npm start` didn't work for me, so I fixed that
- I thought it was annoying that `npm run watch` (and therefore `npm start`) didn't build right away and instead waited for the first change. I fixed that.
- The `init` script is cool AF. However, there were quite a few references to the original template/author/URLs that didn't belong. I made a few changes to the script to fix that.
- `rollup-plugin-typescript` is super abandoned, so I upgraded to `@rollup/plugin-typescript`

To see the changes more split up, you can see the individual commits.

I have a couple of other changes I was thinking about, but they may be more difficult or controversial, so I started with the easier ones. I'll make another Pull Request if I end up trying those changes.

(The 2 big ones are:

- Add a `.tsconfig`. Easy, but maybe controversial.
- Make a script similar to `init` to assist with versioning. More effort than I want to put in at the moment.

)

### CODE REVIEW

**Review by wisnia74 — COMMENTED** [review]
I've seen that you've linked my template in your mod `README.md` - that's cool man, appreciate that you find it useful. You've pointed a couple of nice improvements - I'll have a look, maybe introduce some small wording changes and merge it.

> "I thought it was annoying that npm run watch (and therefore npm start) didn't build right away(...)"

Yeah, good point.

> The init script is cool AF.

I think so too - it makes it easier to setup the template. If you'll look at the very beginnings of this repo, the idea was to have template completely generated from `.js` scripts, but it ended up getting to complicated imho (for potential users). I had a CI to check if generating it works, tests pass and so on, but I think it's better to just keep it simple. If you're curious how it looked like, pull latest `master` and run `git checkout d0fce1ee5423eea308ee1ff0709e2cc27e2d88f4`.

> Add a .tsconfig. Easy, but maybe controversial

I was thinking about it and I think I'll actually do it today, at least for resolving paths from `./src`.
Edit: that's a lie - I'll do it sometime soon though.

>Make a script similar to init to assist with versioning. More effort than I want to put in at the moment.

You're reading my mind! However I'm working on a mod that calculates max-min amount of money guests spawn with. It takes some time and I figured that when I have it in place, then I'll go back here, figure out release script and then also upload the mod.

**Review by wisnia74 — APPROVED** [review]

**Comment by mgovea** [comment]
> However I'm working on a mod that calculates max-min amount of money guests spawn with.

Uhhhhhhhhhhhh hmmmmm. I was thinking about that basic idea, except integrating it into a Park Price Manager (to pair with Ride Price Manager). Do you want to team up on this? I was more focused on setting the park price *before* it hits the guest cash starting min by figuring out the park value, and letting the user just set the max price. (I.e. `parkPrice = min(minStartingCash, priceFromParkValue)` The trouble with my idea is that the max price is different per scenario, so it would cause configuration issues when people forget to switch their settings when changing maps.

**Comment by wisnia74** [comment]
@mgovea So I actually have the algorithm ready - it's been tested on a bigger park with 1700+ guests with no real performance drop even when you speed up the game to the highest.

I solved most of the challanges I faced there, like:
- not calling `map.getAllEntities('peep')` more than once per tick because it hits performance MASSIVELY
- not checking for new guests every tick, but for example every `x` ticks
- figuring out which guests to check

Here's raw algorithm (garbage code) - https://pastebin.pl/view/f1b56a10.

I have it written functionally, it's way better performance wise. I'm working to just turn it into a class, then I'll release as a standalone mod. However, feel free to do whatever you like with this code for now.

**Comment by wisnia74** [comment]
BTW I'd love to team up, it's just - I don't really have much time to work on all this. I barely figured out this algorithm to count cash levels. There were months when I just didn't touch it at all 😅 Now my goal is to at least bring it to a usable form and release it. Once I release I can let you know, so you can use whatever you need from it.

**Pull request merged**
